include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.mocks.dart"
    - "**/core/localization/generated/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    avoid_function_literals_in_foreach_calls: false
    avoid_annotating_with_dynamic: true
    always_declare_return_types: true
    unnecessary_new: true
    avoid_empty_else: true
    directives_ordering: true
    avoid_unused_constructor_parameters: true
    prefer_relative_imports: true
    curly_braces_in_flow_control_structures: false
    constant_identifier_names: false
    empty_catches: false
    depend_on_referenced_packages: false
    use_key_in_widget_constructors: false
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: false
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: false
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    no_duplicate_case_values: true
    sort_constructors_first: true
    no_leading_underscores_for_local_identifiers: true
    avoid_void_async: true
