name: flutter_ocr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  ffi: ^2.1.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/models/
